name: Run WebdriverIO Tests

on:
  push:
    branches:
      - web
      - api
    paths-ignore:
      - '**/*.md'
  # schedule:
    # - cron: '0 0 * * *' # Adjust as needed
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    container:
      image: ${{ secrets.DEFAULT_DOCKER_IMAGE }}

    env:
      IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x build.sh

      - name: Run build
        run: ./build.sh

      - name: Run tests
        run: npx wdio ./data-science/run/pb.chatbot.run.ts | tee test-output.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: |
            _results/
            _results/data-science
            _results/light-report
            _results/mochawesome
            _results/wdio-logs
            _results/screenshots
            *.log
          retention-days: 2
